### ISSUE TITLE
No labels for Atom Settings or new tabs

### ISSUE THREAD

**Issue by jcready** [joshwcomeau/nice-index#2]
Enabled:

![](https://i.imgur.com/sg3QH2f.png)

Disabled:

![](https://i.imgur.com/WDzBT6j.png)

**Comment by dorian-marchal** [comment]
Same thing for new files (and search tab, as well).

before :
![capture du 2016-07-12 10 23 19](https://cloud.githubusercontent.com/assets/6225979/16760163/c262cd18-481a-11e6-800a-48812fc4390a.png)
after :
![capture du 2016-07-12 10 23 42](https://cloud.githubusercontent.com/assets/6225979/16760169/c4afbfb8-481a-11e6-9a68-1f022183c85e.png)

**Comment by joshwcomeau** [comment]
Yeah, this is an issue that has been annoying me for some time, lol.

I've looked into it a bit, but there's a lot that I don't know about how Atom works internally. Sadly, I don't see this being fixed any time soon :(

**Comment by dorian-marchal** [comment]
#4 should fix this :+1:

**Comment by joshwcomeau** [comment]
Wonderful! Thanks @dorian-marchal. Such a simple fix!

Published as 1.0.2, because I didn't realize `apm publish patch` would auto-increment it.
